repos:
-   repo: https://github.com/ambv/black
    rev: 21.9b0
    hooks:
    - id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v1.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []